version: '3'

services:
  vulnerable-flask:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
